# Generated by Django 4.1 on 2022-09-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0014_alter_siteinfo_siteconfig_name_cn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=20, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=20, verbose_name='中文名')),
            ],
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='RSS地址')),
                ('refresh_time', models.IntegerField(verbose_name='刷新间隔分钟')),
                ('siteinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteinfo', to='sites.siteinfo')),
            ],
        ),
    ]
