# Generated by Django 4.1 on 2022-09-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_alter_tools_name'),
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('keyword', models.CharField(max_length=100, null=True, verbose_name='关键字,使用逗号分隔')),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='rss.config')),
                ('tools_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='download.tools')),
            ],
        ),
    ]
