# Generated by Django 4.1 on 2022-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态启用，禁用'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='规则名称'),
        ),
    ]
