# Generated by Django 4.1 on 2022-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rule_status_alter_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='refresh_time',
        ),
        migrations.AddField(
            model_name='rule',
            name='refresh_time',
            field=models.IntegerField(default=5, verbose_name='刷新间隔分钟'),
        ),
    ]
