# Generated by Django 4.1 on 2022-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0013_alter_job_sites'),
        ('rss', '0005_rule_crontab_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='crontab_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='cron.job'),
        ),
    ]
