# Generated by Django 4.0.3 on 2022-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_seedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='url',
            field=models.URLField(blank=True, max_length=350, verbose_name='RSS地址'),
        ),
    ]
