# Generated by Django 4.0.3 on 2022-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0008_alter_config_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedinfo',
            name='seed_published_time',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
