# Generated by Django 4.0.3 on 2022-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_alter_seedinfo_seed_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedinfo',
            name='seed_file_size',
            field=models.BigIntegerField(verbose_name='种子文件大小'),
        ),
    ]
