# Generated by Django 4.0.3 on 2022-09-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_alter_siteinfo_siteconfig_name_cn'),
        ('rss', '0010_alter_seedinfo_seed_file_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seedinfo',
            unique_together={('seed_hash_id', 'siteinfo_id')},
        ),
    ]
