# Generated by Django 4.0.3 on 2022-09-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0011_alter_seedinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedinfo',
            name='rule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.rule'),
        ),
    ]
