# Generated by Django 4.0.3 on 2022-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0012_seedinfo_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedinfo',
            name='seed_torrent_id',
            field=models.IntegerField(null=True, verbose_name='在下载器的标识ID'),
        ),
    ]
