# Generated by Django 4.0.3 on 2022-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0013_seedinfo_seed_torrent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rate',
            field=models.CharField(max_length=10, null=True, verbose_name='码率:空,1080,2060'),
        ),
    ]
