# Generated by Django 4.0.3 on 2022-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0014_rule_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rate',
            field=models.CharField(default='all', max_length=10, verbose_name='码率:all,1080,2060'),
        ),
    ]
