# Generated by Django 4.0.3 on 2022-09-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0015_alter_rule_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='是否立刻下载'),
        ),
    ]
