# Generated by Django 4.1 on 2022-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0016_rule_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='自定义配置名称'),
        ),
        migrations.AlterField(
            model_name='config',
            name='url',
            field=models.URLField(blank=True, max_length=350, unique=True, verbose_name='RSS地址'),
        ),
    ]
