# Generated by Django 4.1 on 2022-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0017_config_name_alter_config_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='url',
            field=models.URLField(blank=True, max_length=350, verbose_name='RSS地址'),
        ),
    ]
