# Generated by Django 4.1 on 2022-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='下载器名称'),
        ),
    ]
