# Generated by Django 4.0.2 on 2022-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('type_id', models.IntegerField(verbose_name='类型ID')),
            ],
            options={
                'unique_together': {('name', 'type_id')},
            },
        ),
    ]
