# Generated by Django 4.0.2 on 2022-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobtype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='type_id',
            field=models.IntegerField(unique=True, verbose_name='类型ID'),
        ),
    ]
