# Generated by Django 4.0.2 on 2022-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_alter_jobtype_unique_together_alter_jobtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='任务名称')),
                ('jobtype_id', models.IntegerField(verbose_name='类型ID,签到任务只允许配置一个')),
                ('cron_time_type', models.CharField(max_length=10, verbose_name='执行周期类型,秒,分,时,天,周,月')),
                ('crontab', models.CharField(max_length=100, verbose_name='执行时间')),
                ('crontab_id', models.CharField(max_length=64, verbose_name='执行时间')),
                ('crontab_status', models.BooleanField(default=True, verbose_name='任务状态,运行,禁用')),
                ('week', models.IntegerField(verbose_name='周')),
                ('day', models.IntegerField(verbose_name='天')),
                ('hour', models.IntegerField(verbose_name='时')),
                ('minute', models.IntegerField(verbose_name='分')),
                ('second', models.IntegerField(verbose_name='秒')),
            ],
        ),
    ]
