# Generated by Django 4.0.2 on 2022-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='cron_time_type',
            new_name='crontab_time_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='crontab',
        ),
        migrations.AddField(
            model_name='job',
            name='crontab_time',
            field=models.CharField(max_length=100, null=True, verbose_name='执行周期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='crontab_id',
            field=models.CharField(max_length=64, verbose_name='执行ID'),
        ),
    ]
