# Generated by Django 4.0.2 on 2022-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_rename_cron_time_type_job_crontab_time_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sites',
            field=models.CharField(max_length=300, null=True, verbose_name='站点,使用,号分割'),
        ),
    ]
