# Generated by Django 4.0.2 on 2022-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0005_job_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='day',
            field=models.IntegerField(default=0, verbose_name='天'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='时'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minute',
            field=models.IntegerField(default=0, verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='job',
            name='second',
            field=models.IntegerField(default=0, verbose_name='秒'),
        ),
        migrations.AlterField(
            model_name='job',
            name='week',
            field=models.IntegerField(default=0, verbose_name='周'),
        ),
    ]
