# Generated by Django 4.0.2 on 2022-02-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0006_alter_job_day_alter_job_hour_alter_job_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notifys',
            field=models.CharField(max_length=100, null=True, verbose_name='通知类型,使用,号分割'),
        ),
    ]
