# Generated by Django 4.0.2 on 2022-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0007_job_notifys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('type_id', models.IntegerField(verbose_name='类型ID')),
                ('crontab_id', models.CharField(max_length=64, verbose_name='执行ID')),
                ('message', models.CharField(max_length=300, verbose_name='日志记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='是否执行成功')),
            ],
        ),
    ]
