# Generated by Django 4.0.2 on 2022-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
