# Generated by Django 4.0.2 on 2022-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0009_alter_log_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='crontab_time',
            field=models.CharField(max_length=100, null=True, verbose_name='执行周期,* * * * *'),
        ),
    ]
