# Generated by Django 4.0.2 on 2022-03-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0010_alter_job_crontab_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='site_name',
            field=models.CharField(max_length=50, null=True, verbose_name='站点名称'),
        ),
    ]
