# Generated by Django 4.1 on 2022-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0011_log_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='day',
            field=models.CharField(default='*', max_length=50, verbose_name='天'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hour',
            field=models.CharField(default='*', max_length=50, verbose_name='时'),
        ),
        migrations.AlterField(
            model_name='job',
            name='minute',
            field=models.CharField(default='*', max_length=50, verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='job',
            name='second',
            field=models.CharField(default='*', max_length=50, verbose_name='秒'),
        ),
        migrations.AlterField(
            model_name='job',
            name='week',
            field=models.CharField(default='*', max_length=50, verbose_name='周'),
        ),
    ]
