# Generated by Django 4.1 on 2022-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0012_alter_job_day_alter_job_hour_alter_job_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sites',
            field=models.CharField(max_length=800, null=True, verbose_name='站点,使用,号分割'),
        ),
    ]
