# Generated by Django 4.0.2 on 2022-03-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_backupinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaiDuOcr',
        ),
    ]
