# Generated by Django 4.0.2 on 2022-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='级别名称')),
                ('site_name', models.CharField(max_length=50, verbose_name='网站名简称,英文')),
                ('download', models.CharField(max_length=50, verbose_name='下载量')),
                ('up_time', models.CharField(max_length=50, verbose_name='升级时间')),
                ('upload', models.CharField(max_length=50, verbose_name='上传量')),
                ('ratio', models.CharField(max_length=20, verbose_name='魔力')),
                ('privilege', models.CharField(max_length=200, verbose_name='信息说明')),
                ('serial_number', models.IntegerField(verbose_name='排序序号')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名简称,英文')),
                ('name_cn', models.CharField(max_length=50, verbose_name='网站名简称,中文')),
                ('index_url', models.CharField(max_length=200, verbose_name='首页地址')),
                ('torrent_url', models.CharField(max_length=200, verbose_name='种子地址')),
                ('bonus_url', models.CharField(max_length=200, verbose_name='魔力地址')),
                ('sign_url', models.CharField(max_length=200, verbose_name='签到地址')),
            ],
            options={
                'unique_together': {('name', 'name_cn', 'index_url')},
            },
        ),
    ]
