# Generated by Django 4.0.2 on 2022-02-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_siterank_ratio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siterank',
            unique_together={('name', 'site_name')},
        ),
    ]
