# Generated by Django 4.0.2 on 2022-02-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_siterank_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteConfig',
        ),
        migrations.RenameField(
            model_name='siterank',
            old_name='site_name',
            new_name='siteconfig_name',
        ),
        migrations.AlterUniqueTogether(
            name='siterank',
            unique_together={('name', 'siteconfig_name')},
        ),
    ]
