# Generated by Django 4.0.2 on 2022-02-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_rename_site_siteconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteconfig_name', models.CharField(max_length=50, unique=True, verbose_name='网站名简称,英文')),
                ('cookie', models.CharField(max_length=300, verbose_name='网站cookie信息')),
                ('passkey', models.CharField(max_length=100, verbose_name='网站秘钥')),
            ],
        ),
    ]
