# Generated by Django 4.0.2 on 2022-02-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='cookie',
            field=models.CharField(max_length=800, verbose_name='网站cookie信息'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='passkey',
            field=models.CharField(max_length=200, verbose_name='网站秘钥'),
        ),
    ]
