# Generated by Django 4.0.2 on 2022-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_siteinfo_cookie_alter_siteinfo_passkey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siteconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='index_url',
            field=models.CharField(max_length=200, unique=True, verbose_name='首页地址'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='网站名简称,英文'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='name_cn',
            field=models.CharField(max_length=50, unique=True, verbose_name='网站名简称,中文'),
        ),
    ]
