# Generated by Django 4.0.2 on 2022-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_siteconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='action',
            field=models.CharField(max_length=20, null=True, verbose_name='判断使用post还是get'),
        ),
    ]
