# Generated by Django 4.0.2 on 2022-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_siteconfig_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='is_sign',
            field=models.BooleanField(default=True, verbose_name='是否有签到功能'),
        ),
    ]
