# Generated by Django 4.0.3 on 2022-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_remove_siteconfig_action_remove_siteconfig_is_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sign_type',
            field=models.CharField(max_length=20, null=True, verbose_name='签到类型,统一签到少改代码'),
        ),
    ]
