# Generated by Django 4.0.3 on 2022-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_siteconfig_sign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='siteconfig_name_cn',
            field=models.CharField(default='', max_length=50, verbose_name='网站名简称,中文'),
        ),
    ]
