# Generated by Django 4.1 on 2022-08-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_siteinfo_siteconfig_name_cn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='siteconfig_name_cn',
            field=models.CharField(max_length=50, null=True, verbose_name='网站名简称,中文'),
        ),
    ]
