# Generated by Django 4.1 on 2022-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='invite',
            field=models.IntegerField(default=0, verbose_name='邀请数量'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='totle_seed_size',
            field=models.CharField(default=0, max_length=20, verbose_name='做种体积'),
        ),
    ]
