# Generated by Django 4.1 on 2022-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_siteuser_invite_siteuser_totle_seed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='cookie',
            field=models.CharField(max_length=1500, verbose_name='网站cookie信息'),
        ),
    ]
