# Generated by Django 4.1 on 2022-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_alter_siteinfo_cookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='代理名称')),
                ('address', models.CharField(max_length=128, verbose_name='代理地址')),
                ('ptype', models.CharField(max_length=5, verbose_name='代理类型 http,socks')),
                ('port', models.IntegerField(verbose_name='代理端口')),
                ('username', models.CharField(max_length=50, verbose_name='账号')),
                ('userpassword', models.CharField(max_length=128, verbose_name='密码')),
            ],
        ),
    ]
