# Generated by Django 4.1 on 2022-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_siteproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproxy',
            name='ptype',
            field=models.CharField(max_length=10, verbose_name='代理类型 http,socks5'),
        ),
    ]
