# Generated by Django 4.1 on 2022-10-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_alter_siteproxy_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='siteproxy_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteproxy', to='sites.siteproxy'),
        ),
    ]
