# Generated by Django 4.0.2 on 2022-02-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyconfig',
            name='smtp_port',
            field=models.IntegerField(default=25, verbose_name='发信端口'),
        ),
        migrations.AlterField(
            model_name='notifyconfig',
            name='tg_chat_id',
            field=models.BigIntegerField(default=0, verbose_name='频道ID或自身id'),
        ),
    ]
