# Generated by Django 4.0.2 on 2022-02-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alter_notifyconfig_smtp_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyconfig',
            name='mail_type',
            field=models.CharField(max_length=10, null=True, verbose_name='发件邮箱类型:qq,sina,163'),
        ),
    ]
